### ISSUE TITLE
Aquestion about loss calculation

### ISSUE THREAD

**Issue by MarserHK** [Hope1337/YOWOv3#28]
"Hello, I created a dataset in UCF format, and encountered the following error during the 5th training round. How should I resolve this?"

```
epoch : 5, update : 110, loss = 4.063435941934586
epoch : 5, update : 111, loss = 4.644285038113594
epoch : 5, update : 112, loss = 4.076864972710609
epoch : 5, update : 113, loss = 4.056785270571709
Traceback (most recent call last):
  File "main.py", line 16, in <module>
    train.train_model(config=config)
  File "/home/nvidia/fourT/hwt/YOWOv3-main/scripts/train.py", line 112, in train_model
    loss = criterion(outputs, targets) / acc_grad
  File "/home/nvidia/fourT/hwt/YOWOv3-main/utils/loss.py", line 102, in __call__
    target_bboxes, target_scores, fg_mask = self.assign(scores, bboxes,
ValueError: too many values to unpack (expected 3)
```

**Comment by Hope1337** [comment]
@MarserHK There seems to be a batch that contains all images for which there are no bounding boxes. [This line](https://github.com/Hope1337/YOWOv3/blob/40e4f8ef5467469df56cd6c96129ed10b8d2128b/utils/loss.py#L160) returns more than 3 values and causes an error

**Comment by MarserHK** [comment]
Hello, but I checked my label data and didn't find any empty txt label files. Moreover, I ran the training again and it could reach the 7th round, but I noticed that the error occurs every time when saving the model.
```
epoch : 7, update : 109, loss = 4.220024660229683
epoch : 7, update : 110, loss = 3.662436217069626
epoch : 7, update : 111, loss = 4.221729964017868
epoch : 7, update : 112, loss = 4.394728496670723
epoch : 7, update : 113, loss = 4.131817564368248
Traceback (most recent call last):
  File "main.py", line 16, in <module>
    train.train_model(config=config)
  File "/home/nvidia/fourT/hwt/YOWOv3-main/scripts/train.py", line 112, in train_model
    loss = criterion(outputs, targets) / acc_grad
  File "/home/nvidia/fourT/hwt/YOWOv3-main/utils/loss.py", line 102, in __call__
    target_bboxes, target_scores, fg_mask = self.assign(scores, bboxes,
ValueError: too many values to unpack (expected 3)
```

**Comment by Hope1337** [comment]
@MarserHK You should add some line to check if [this condition](https://github.com/Hope1337/YOWOv3/blob/40e4f8ef5467469df56cd6c96129ed10b8d2128b/utils/loss.py#L160) is satisfied. May  be the transform pipeline dropped your annotation and if batch_size too small, the condition will causes an error.

**Comment by MarserHK** [comment]
Thank you for your work！ I have successfully trained, but I don't know how to perform inference on videos

**Comment by Hope1337** [comment]
@MarserHK You can convert your video into sequence of frames and make use the ```scripts/live.py``` code.

**Comment by MarserHK** [comment]
"Thank you for your reply. I modified the live.py file to perform video inference, but the result of the inference is like this. What could have caused this situation?"
![3](https://github.com/user-attachments/assets/4a46339f-fb2c-44f5-811c-ee58b2dae5ed)

**Comment by Hope1337** [comment]
@MarserHK Hard to say without specific context, there are potentially various of causes.

**Comment by Zerobub** [comment]
> “谢谢你的回复。我修改了 live.py 文件来执行视频推理，但推理的结果像这样。是什么导致了这种情况？ ![3](https://private-user-images.githubusercontent.com/139473326/378650811-4a46339f-fb2c-44f5-811c-ee58b2dae5ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxOTA1MzcsIm5iZiI6MTczMDE5MDIzNywicGF0aCI6Ii8xMzk0NzMzMjYvMzc4NjUwODExLTRhNDYzMzlmLWZiMmMtNDRmNS04MTFjLWVlNThiMmRhZTVlZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyOVQwODIzNTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mODllMmFhOGFhMTBlZjg0YzAxMjhjNjE3YjYzNmYwMzk2ZDE0OGE1MzA0OTk4NzM3MDA1OTE1YzI4NjBiYWRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.R2qEcigr4qAnryYuPSRZESNXThPSa6q2Gzt9JPoeQ9k)

Could you tell me how you modified the live.py file? I would like to try running inference on a video. Thanks

**Comment by MarserHK** [comment]
This is my live.py
```
`import torch
import torch.utils.data as data
import torchvision.transforms.functional as FT
import cv2
from PIL import Image
from utils.box import draw_bounding_box
from utils.box import non_max_suppression
from model.TSN.YOWOv3 import build_yowov3
from utils.build_config import build_config
from utils.flops import get_info


class VideoTransform():
    """
    Transform video frames for model input
    """

    def __init__(self, img_size):
        self.img_size = img_size

    def to_tensor(self, image):
        return FT.to_tensor(image)

    def normalize(self, clip, mean=[0.4345, 0.4051, 0.3775], std=[0.2768, 0.2713, 0.2737]):
        mean = torch.FloatTensor([0.485, 0.456, 0.406]).view(-1, 1, 1)
        std = torch.FloatTensor([0.229, 0.224, 0.225]).view(-1, 1, 1)
        clip -= mean
        clip /= std
        return clip

    def __call__(self, img):
        W, H = img.size
        img = img.resize([self.img_size, self.img_size])
        img = self.to_tensor(img)
        img = self.normalize(img)
        return img


def detect(config, video_path):
    # 初始化模型
    model = build_yowov3(config)
    get_info(config, model)
    model.to("cuda")
    model.eval()
    mapping = config['idx2name']

    # 打开视频文件
    cap = cv2.VideoCapture(video_path)

    # 获取视频信息
    fps = int(cap.get(cv2.CAP_PROP_FPS))
    frame_width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    frame_height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))

    # 可选:设置输出视频
    fourcc = cv2.VideoWriter_fourcc(*'mp4v')
    out = cv2.VideoWriter('output.mp4', fourcc, fps, (config['img_size'], config['img_size']))

    frame_list = []
    transform = VideoTransform(config['img_size'])

    while cap.isOpened():
        ret, frame = cap.read()
        if not ret:
            break

        # 转换帧格式并处理
        origin_image = Image.fromarray(cv2.cvtColor(frame, cv2.COLOR_BGR2RGB))
        frame_list.append(transform(origin_image))

        if len(frame_list) > 16:
            frame_list.pop(0)
        if len(frame_list) < 16:
            continue

        # 准备模型输入
        clip = torch.stack(frame_list, 0).permute(1, 0, 2, 3).contiguous()
        clip = clip.unsqueeze(0).to("cuda")

        # 模型推理
        outputs = model(clip)
        outputs = non_max_suppression(outputs, conf_threshold=0.5, iou_threshold=0.5)[0]

        # 处理输出帧
        origin_image = cv2.resize(frame, (config['img_size'], config['img_size']))
        draw_bounding_box(origin_image, outputs[:, :4], outputs[:, 5], outputs[:, 4], mapping)

        # 写入输出视频
        out.write(origin_image)

        # 显示处理后的帧
        # cv2.imshow('Video Detection', origin_image)

        if cv2.waitKey(1) & 0xFF == ord('q'):
            break

    cap.release()
    out.release()
    cv2.destroyAllWindows()


if __name__ == "__main__":
    config = build_config()
    video_path = r"/home/nvidia/fourT/hwt/YOWOv3-main/video/leaning_no3_005.mp4"  # 替换为您的视频路径
    detect(config, video_path)`
```

**Comment by MarserHK** [comment]
> > “谢谢你的回复。我修改了 live.py 文件来执行视频推理，但推理的结果像这样。是什么导致了这种情况？ ![3](https://private-user-images.githubusercontent.com/139473326/378650811-4a46339f-fb2c-44f5-811c-ee58b2dae5ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxOTA1MzcsIm5iZiI6MTczMDE5MDIzNywicGF0aCI6Ii8xMzk0NzMzMjYvMzc4NjUwODExLTRhNDYzMzlmLWZiMmMtNDRmNS04MTFjLWVlNThiMmRhZTVlZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyOVQwODIzNTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mODllMmFhOGFhMTBlZjg0YzAxMjhjNjE3YjYzNmYwMzk2ZDE0OGE1MzA0OTk4NzM3MDA1OTE1YzI4NjBiYWRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.R2qEcigr4qAnryYuPSRZESNXThPSa6q2Gzt9JPoeQ9k)
> 
> Could you tell me how you modified the live.py file? I would like to try running inference on a video. Thanks
this is my live.py
```
import torch
import torch.utils.data as data
import torchvision.transforms.functional as FT
import cv2
from PIL import Image
from utils.box import draw_bounding_box
from utils.box import non_max_suppression
from model.TSN.YOWOv3 import build_yowov3
from utils.build_config import build_config
from utils.flops import get_info


class VideoTransform():
    """
    Transform video frames for model input
    """

    def __init__(self, img_size):
        self.img_size = img_size

    def to_tensor(self, image):
        return FT.to_tensor(image)

    def normalize(self, clip, mean=[0.4345, 0.4051, 0.3775], std=[0.2768, 0.2713, 0.2737]):
        mean = torch.FloatTensor([0.485, 0.456, 0.406]).view(-1, 1, 1)
        std = torch.FloatTensor([0.229, 0.224, 0.225]).view(-1, 1, 1)
        clip -= mean
        clip /= std
        return clip

    def __call__(self, img):
        W, H = img.size
        img = img.resize([self.img_size, self.img_size])
        img = self.to_tensor(img)
        img = self.normalize(img)
        return img


def detect(config, video_path):
    # 初始化模型
    model = build_yowov3(config)
    get_info(config, model)
    model.to("cuda")
    model.eval()
    mapping = config['idx2name']

    # 打开视频文件
    cap = cv2.VideoCapture(video_path)

    # 获取视频信息
    fps = int(cap.get(cv2.CAP_PROP_FPS))
    frame_width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    frame_height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))

    # 可选:设置输出视频
    fourcc = cv2.VideoWriter_fourcc(*'mp4v')
    out = cv2.VideoWriter('output.mp4', fourcc, fps, (config['img_size'], config['img_size']))

    frame_list = []
    transform = VideoTransform(config['img_size'])

    while cap.isOpened():
        ret, frame = cap.read()
        if not ret:
            break

        # 转换帧格式并处理
        origin_image = Image.fromarray(cv2.cvtColor(frame, cv2.COLOR_BGR2RGB))
        frame_list.append(transform(origin_image))

        if len(frame_list) > 16:
            frame_list.pop(0)
        if len(frame_list) < 16:
            continue

        # 准备模型输入
        clip = torch.stack(frame_list, 0).permute(1, 0, 2, 3).contiguous()
        clip = clip.unsqueeze(0).to("cuda")

        # 模型推理
        outputs = model(clip)
        outputs = non_max_suppression(outputs, conf_threshold=0.5, iou_threshold=0.5)[0]

        # 处理输出帧
        origin_image = cv2.resize(frame, (config['img_size'], config['img_size']))
        draw_bounding_box(origin_image, outputs[:, :4], outputs[:, 5], outputs[:, 4], mapping)

        # 写入输出视频
        out.write(origin_image)

        # 显示处理后的帧
        # cv2.imshow('Video Detection', origin_image)

        if cv2.waitKey(1) & 0xFF == ord('q'):
            break

    cap.release()
    out.release()
    cv2.destroyAllWindows()


if __name__ == "__main__":
    config = build_config()
    video_path = r"/home/nvidia/fourT/hwt/YOWOv3-main/video/leaning_no3_005.mp4"  # 替换为您的视频路径
    detect(config, video_path)
```

**Comment by Zerobub** [comment]
> > > “谢谢你的回复。我修改了 live.py 文件来执行视频推理，但推理的结果像这样。是什么导致了这种情况？ ![3](https://private-user-images.githubusercontent.com/139473326/378650811-4a46339f-fb2c-44f5-811c-ee58b2dae5ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxOTA1MzcsIm5iZiI6MTczMDE5MDIzNywicGF0aCI6Ii8xMzk0NzMzMjYvMzc4NjUwODExLTRhNDYzMzlmLWZiMmMtNDRmNS04MTFjLWVlNThiMmRhZTVlZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyOVQwODIzNTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mODllMmFhOGFhMTBlZjg0YzAxMjhjNjE3YjYzNmYwMzk2ZDE0OGE1MzA0OTk4NzM3MDA1OTE1YzI4NjBiYWRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.R2qEcigr4qAnryYuPSRZESNXThPSa6q2Gzt9JPoeQ9k)
> > 
> > 
> > Could you tell me how you modified the live.py file? I would like to try running inference on a video. Thanks
> > this is my live.py
> 
> ```
> import torch
> import torch.utils.data as data
> import torchvision.transforms.functional as FT
> import cv2
> from PIL import Image
> from utils.box import draw_bounding_box
> from utils.box import non_max_suppression
> from model.TSN.YOWOv3 import build_yowov3
> from utils.build_config import build_config
> from utils.flops import get_info
> 
> 
> class VideoTransform():
>     """
>     Transform video frames for model input
>     """
> 
>     def __init__(self, img_size):
>         self.img_size = img_size
> 
>     def to_tensor(self, image):
>         return FT.to_tensor(image)
> 
>     def normalize(self, clip, mean=[0.4345, 0.4051, 0.3775], std=[0.2768, 0.2713, 0.2737]):
>         mean = torch.FloatTensor([0.485, 0.456, 0.406]).view(-1, 1, 1)
>         std = torch.FloatTensor([0.229, 0.224, 0.225]).view(-1, 1, 1)
>         clip -= mean
>         clip /= std
>         return clip
> 
>     def __call__(self, img):
>         W, H = img.size
>         img = img.resize([self.img_size, self.img_size])
>         img = self.to_tensor(img)
>         img = self.normalize(img)
>         return img
> 
> 
> def detect(config, video_path):
>     # 初始化模型
>     model = build_yowov3(config)
>     get_info(config, model)
>     model.to("cuda")
>     model.eval()
>     mapping = config['idx2name']
> 
>     # 打开视频文件
>     cap = cv2.VideoCapture(video_path)
> 
>     # 获取视频信息
>     fps = int(cap.get(cv2.CAP_PROP_FPS))
>     frame_width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
>     frame_height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
> 
>     # 可选:设置输出视频
>     fourcc = cv2.VideoWriter_fourcc(*'mp4v')
>     out = cv2.VideoWriter('output.mp4', fourcc, fps, (config['img_size'], config['img_size']))
> 
>     frame_list = []
>     transform = VideoTransform(config['img_size'])
> 
>     while cap.isOpened():
>         ret, frame = cap.read()
>         if not ret:
>             break
> 
>         # 转换帧格式并处理
>         origin_image = Image.fromarray(cv2.cvtColor(frame, cv2.COLOR_BGR2RGB))
>         frame_list.append(transform(origin_image))
> 
>         if len(frame_list) > 16:
>             frame_list.pop(0)
>         if len(frame_list) < 16:
>             continue
> 
>         # 准备模型输入
>         clip = torch.stack(frame_list, 0).permute(1, 0, 2, 3).contiguous()
>         clip = clip.unsqueeze(0).to("cuda")
> 
>         # 模型推理
>         outputs = model(clip)
>         outputs = non_max_suppression(outputs, conf_threshold=0.5, iou_threshold=0.5)[0]
> 
>         # 处理输出帧
>         origin_image = cv2.resize(frame, (config['img_size'], config['img_size']))
>         draw_bounding_box(origin_image, outputs[:, :4], outputs[:, 5], outputs[:, 4], mapping)
> 
>         # 写入输出视频
>         out.write(origin_image)
> 
>         # 显示处理后的帧
>         # cv2.imshow('Video Detection', origin_image)
> 
>         if cv2.waitKey(1) & 0xFF == ord('q'):
>             break
> 
>     cap.release()
>     out.release()
>     cv2.destroyAllWindows()
> 
> 
> if __name__ == "__main__":
>     config = build_config()
>     video_path = r"/home/nvidia/fourT/hwt/YOWOv3-main/video/leaning_no3_005.mp4"  # 替换为您的视频路径
>     detect(config, video_path)
> ```



> > > “谢谢你的回复。我修改了 live.py 文件来执行视频推理，但推理的结果像这样。是什么导致了这种情况？ ![3](https://private-user-images.githubusercontent.com/139473326/378650811-4a46339f-fb2c-44f5-811c-ee58b2dae5ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxOTA1MzcsIm5iZiI6MTczMDE5MDIzNywicGF0aCI6Ii8xMzk0NzMzMjYvMzc4NjUwODExLTRhNDYzMzlmLWZiMmMtNDRmNS04MTFjLWVlNThiMmRhZTVlZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyOVQwODIzNTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mODllMmFhOGFhMTBlZjg0YzAxMjhjNjE3YjYzNmYwMzk2ZDE0OGE1MzA0OTk4NzM3MDA1OTE1YzI4NjBiYWRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.R2qEcigr4qAnryYuPSRZESNXThPSa6q2Gzt9JPoeQ9k)
> > 
> > 
> > Could you tell me how you modified the live.py file? I would like to try running inference on a video. Thanks
> > this is my live.py
> 
> ```
> import torch
> import torch.utils.data as data
> import torchvision.transforms.functional as FT
> import cv2
> from PIL import Image
> from utils.box import draw_bounding_box
> from utils.box import non_max_suppression
> from model.TSN.YOWOv3 import build_yowov3
> from utils.build_config import build_config
> from utils.flops import get_info
> 
> 
> class VideoTransform():
>     """
>     Transform video frames for model input
>     """
> 
>     def __init__(self, img_size):
>         self.img_size = img_size
> 
>     def to_tensor(self, image):
>         return FT.to_tensor(image)
> 
>     def normalize(self, clip, mean=[0.4345, 0.4051, 0.3775], std=[0.2768, 0.2713, 0.2737]):
>         mean = torch.FloatTensor([0.485, 0.456, 0.406]).view(-1, 1, 1)
>         std = torch.FloatTensor([0.229, 0.224, 0.225]).view(-1, 1, 1)
>         clip -= mean
>         clip /= std
>         return clip
> 
>     def __call__(self, img):
>         W, H = img.size
>         img = img.resize([self.img_size, self.img_size])
>         img = self.to_tensor(img)
>         img = self.normalize(img)
>         return img
> 
> 
> def detect(config, video_path):
>     # 初始化模型
>     model = build_yowov3(config)
>     get_info(config, model)
>     model.to("cuda")
>     model.eval()
>     mapping = config['idx2name']
> 
>     # 打开视频文件
>     cap = cv2.VideoCapture(video_path)
> 
>     # 获取视频信息
>     fps = int(cap.get(cv2.CAP_PROP_FPS))
>     frame_width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
>     frame_height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
> 
>     # 可选:设置输出视频
>     fourcc = cv2.VideoWriter_fourcc(*'mp4v')
>     out = cv2.VideoWriter('output.mp4', fourcc, fps, (config['img_size'], config['img_size']))
> 
>     frame_list = []
>     transform = VideoTransform(config['img_size'])
> 
>     while cap.isOpened():
>         ret, frame = cap.read()
>         if not ret:
>             break
> 
>         # 转换帧格式并处理
>         origin_image = Image.fromarray(cv2.cvtColor(frame, cv2.COLOR_BGR2RGB))
>         frame_list.append(transform(origin_image))
> 
>         if len(frame_list) > 16:
>             frame_list.pop(0)
>         if len(frame_list) < 16:
>             continue
> 
>         # 准备模型输入
>         clip = torch.stack(frame_list, 0).permute(1, 0, 2, 3).contiguous()
>         clip = clip.unsqueeze(0).to("cuda")
> 
>         # 模型推理
>         outputs = model(clip)
>         outputs = non_max_suppression(outputs, conf_threshold=0.5, iou_threshold=0.5)[0]
> 
>         # 处理输出帧
>         origin_image = cv2.resize(frame, (config['img_size'], config['img_size']))
>         draw_bounding_box(origin_image, outputs[:, :4], outputs[:, 5], outputs[:, 4], mapping)
> 
>         # 写入输出视频
>         out.write(origin_image)
> 
>         # 显示处理后的帧
>         # cv2.imshow('Video Detection', origin_image)
> 
>         if cv2.waitKey(1) & 0xFF == ord('q'):
>             break
> 
>     cap.release()
>     out.release()
>     cv2.destroyAllWindows()
> 
> 
> if __name__ == "__main__":
>     config = build_config()
>     video_path = r"/home/nvidia/fourT/hwt/YOWOv3-main/video/leaning_no3_005.mp4"  # 替换为您的视频路径
>     detect(config, video_path)
> ```

thank you for your code！！！！！！！

**Comment by jamesbondzhou** [comment]
> Thank you for your work！ I have successfully trained, but I don't know how to perform inference on videos

how did you solve the problem? got the same problem!
