### ISSUE TITLE
Question about eval_ava

### ISSUE THREAD

**Issue by T-wow** [Hope1337/YOWOv3#40]
Hello, after training on the AVA dataset and attempting to run evaluation, I encountered an error. The error message is as follows:
INFO:root:==> 0.724203 seconds to read file evaluator/Evaluation/ava_val_v2.2.csv
INFO:root:==> 20.5886 seconds to convert groundtruth
Traceback (most recent call last):
  File "main.py", line 24, in <module>
    ava_eval.eval(config=config)
  File "/mnt/C/znmd_tjs/YOWOv3-main/scripts/ava_eval.py", line 52, in eval
    get_ava_performance.eval(config)
  File "/mnt/C/znmd_tjs/YOWOv3-main/evaluator/Evaluation/get_ava_performance.py", line 216, in eval
    run_evaluation(**vars(args))
  File "/mnt/C/znmd_tjs/YOWOv3-main/evaluator/Evaluation/get_ava_performance.py", line 158, in run_evaluation
    boxes, labels, scores, _ = read_csv(detections, class_whitelist, 50)
  File "/mnt/C/znmd_tjs/YOWOv3-main/evaluator/Evaluation/get_ava_performance.py", line 71, in read_csv
    assert len(row) in [2, 7, 8], "Wrong number of colum
    How to resolve the Issue,thanks!!

**Comment by T-wow** [comment]
Hello, after training on the AVA dataset and attempting to run evaluation, I encountered an error. The error message is as follows:
INFO:root:==> 0.724203 seconds to read file evaluator/Evaluation/ava_val_v2.2.csv
INFO:root:==> 20.5886 seconds to convert groundtruth
Traceback (most recent call last):
  File "main.py", line 24, in <module>
    ava_eval.eval(config=config)
  File "/mnt/C/znmd_tjs/YOWOv3-main/scripts/ava_eval.py", line 52, in eval
    get_ava_performance.eval(config)
  File "/mnt/C/znmd_tjs/YOWOv3-main/evaluator/Evaluation/get_ava_performance.py", line 216, in eval
    run_evaluation(**vars(args))
  File "/mnt/C/znmd_tjs/YOWOv3-main/evaluator/Evaluation/get_ava_performance.py", line 158, in run_evaluation
    boxes, labels, scores, _ = read_csv(detections, class_whitelist, 50)
  File "/mnt/C/znmd_tjs/YOWOv3-main/evaluator/Evaluation/get_ava_performance.py", line 71, in read_csv
    assert len(row) in [2, 7, 8], "Wrong number of columns: " + row
TypeError: can only concatenate str (not "list") to str
How to resolve the Issue,thanks!!

**Comment by T-wow** [comment]
Can I modify the code as follows?
assert len(row) in [2, 7, 8], "Wrong number of columns: " + row 
-->
assert len(row) in [2, 7, 8], "Wrong number of columns: " + str(row)
